---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ecorp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - ecorp.plaidcloud.io
  rules:
  - host: ecorp.plaidcloud.io
    http:
      paths:
      - backend:
          serviceName: ecorp-wordpress
          servicePort: 80
        path: /
