apiVersion: v2
name: wordpress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: wordpress
    version: 9.0.3
    repository: https://charts.helm.sh/stable

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-hooli
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - newhooli.plaidcloud.io
  rules:
  - host: newhooli.plaidcloud.io
    http:
      paths:
      - backend:
          serviceName: hooli-wordpress
          servicePort: 80
        path: /