---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - hooli.plaidcloud.io
    - app.hooli.plaidcloud.io
    - superset.hooli.plaidcloud.io
    secretName: ssl-cert
  rules:
  - host: hooli.plaidcloud.io
    http:
      paths:
      - backend:
          serviceName: hooli-wordpress
          servicePort: 80
        path: /
  - host: superset.hooli.plaidcloud.io
    http:
      paths:
      - backend:
          serviceName: superset
          servicePort: 9000
        path: /
