---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - hooli.plaidcloud.io
    - app.hooli.plaidcloud.io
    - superset.hooli.plaidcloud.io
    secretName: ssl-cert
  rules:
  - host: hooli.plaidcloud.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hooli-wordpress
            port:
              number: 80
        
  - host: superset.hooli.plaidcloud.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hooli-superset
            port:
              number: 9000
        