---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - hooli.plaidcloud.io
  rules:
  - host: hooli.plaidcloud.io
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
        path: /
