---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-hooli
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - hooli.plaidcloud.io
  rules:
  - host: hooli.plaidcloud.io
    http:
      paths:
      - backend:
          serviceName: hooli-wordpress
          servicePort: 80
        path: /
