apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
spec:
  generators:
    - git:
        repoURL: git@github.com:xsreality/argocd-applicationset-demo.git
        revision: main
        files:
          - path: "argocd/tenants-discovery/**/config.json"
  template:
    metadata:
      name: '{{tenant.name}}-tenant'
    spec:
      project: default
      source:
        repoURL: git@github.com:xsreality/argocd-applicationset-demo.git
        targetRevision: main
        path: 'tenants/{{tenant.name}}'
        helm:
          valueFiles:
            - values.{{tenant.name}}.yaml
      destination:
        server: '{{k8s_cluster.address}}'
        namespace: '{{k8s_cluster.namespace}}'
      syncPolicy: { }
